version: '3.8'

services:
  app:
    image: fastapi-ai-app
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    volumes:
      - ./app:/app/app
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
